# Generated by Django 4.0.3 on 2022-04-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRefugioMascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('colab', 'Colaborador'), ('client', 'Cliente')], default=False, max_length=300),
        ),
    ]
