# Generated by Django 4.0.3 on 2022-04-15 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRefugioMascotas', '0004_remove_user_is_admin_remove_user_is_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50, verbose_name='Especie')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sex', models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra')], max_length=20, verbose_name='Sexo')),
                ('breed', models.CharField(max_length=50, verbose_name='Raza')),
                ('age', models.CharField(max_length=10, verbose_name='Edad')),
                ('vaccination', models.CharField(max_length=50, verbose_name='Vacunacion')),
                ('illness', models.CharField(max_length=150, verbose_name='Enfermedades')),
                ('feeding', models.CharField(max_length=150, verbose_name='Alimentacion')),
                ('rescue_date', models.DateField(verbose_name='Fecha de Rescate')),
                ('description', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('adopter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
