# Generated by Django 4.0.3 on 2022-04-17 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRefugioMascotas', '0008_alter_pets_adopter_alter_pets_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='Pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppRefugioMascotas.pets', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='image',
            field=models.ImageField(default='pet.jpg', upload_to='pet_pics', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Foto de perfil'),
        ),
    ]
