# Generated by Django 4.0.3 on 2022-04-17 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRefugioMascotas', '0009_alter_adoptionrequest_pet_alter_pets_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='Pet',
            field=models.OneToOneField(default='null', on_delete=django.db.models.deletion.CASCADE, to='AppRefugioMascotas.pets', verbose_name='Mascota'),
        ),
    ]
