# Generated by Django 4.0.3 on 2022-04-17 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRefugioMascotas', '0010_alter_adoptionrequest_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='Pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppRefugioMascotas.pets', verbose_name='Mascota'),
        ),
    ]
