# Generated by Django 4.0.3 on 2022-04-17 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRefugioMascotas', '0011_alter_adoptionrequest_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150, verbose_name='Usuario')),
                ('firstName', models.CharField(max_length=150, verbose_name='Nombre')),
                ('lastName', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Número de Telefono')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('addreses', models.CharField(max_length=150, verbose_name='Direccón')),
                ('reason', models.CharField(max_length=150, verbose_name='Motivo para adoptar')),
                ('otherPets', models.CharField(blank=True, max_length=150, verbose_name='Otras Mascotas')),
                ('Pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppRefugioMascotas.pets', verbose_name='Mascota')),
            ],
        ),
        migrations.DeleteModel(
            name='adoptionRequest',
        ),
    ]
