# Generated by Django 4.0.3 on 2022-04-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRefugioMascotas', '0013_failedlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedlogin',
            name='times',
            field=models.IntegerField(default='0', verbose_name='Times'),
        ),
    ]
