# Generated by Django 4.0.3 on 2022-04-21 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppRefugioMascotas', '0014_failedlogin_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedlogin',
            name='user',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
