# Generated by Django 4.0.3 on 2022-05-05 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRefugioMascotas', '0016_historicaladoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPets',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('species', models.CharField(max_length=50, verbose_name='Especie')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('sex', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=20, verbose_name='Sexo')),
                ('breed', models.CharField(max_length=50, verbose_name='Raza')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('vaccination', models.CharField(max_length=50, verbose_name='Vacunacion')),
                ('illness', models.CharField(max_length=150, verbose_name='Enfermedades')),
                ('feeding', models.CharField(max_length=150, verbose_name='Alimentacion')),
                ('rescue_date', models.DateField(verbose_name='Fecha de Rescate')),
                ('description', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('image', models.TextField(default='pet.jpg', max_length=100, verbose_name='Foto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('adopter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Adoptante')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFailedLogin',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('times', models.IntegerField(default='0', verbose_name='Times')),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_column='username', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical failed login',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
